name: Test

on: workflow_call

env:
  NODE_VERSION: 14.19.3
  TZ: 'Asia/Yekaterinburg'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run Test
        run: npm run test
